using Brutal.Numerics;

namespace AirDefence;

/// <summary>
/// Every weapon system the mod knows about.
///
/// <para><b>This is the file to add to.</b> A new launcher, round or sensor is an entry here
/// plus its art; no other C# needs to change. Discovery is by <see cref="LauncherProfile.PartId"/>,
/// so the battery picks up whatever is fitted without anything hardcoding a particular
/// vehicle.</para>
///
/// <para>The launcher geometry below is generated by <c>tools/model/pantsir.py</c> and checked
/// against the exported mesh by <c>tools/validate-parts.py</c>. Rerun the model build and paste
/// what it prints rather than editing the numbers.</para>
/// </summary>
public static class Arsenal
{
    // ---- Munitions ------------------------------------------------------

    /// <summary>57E6: the Pantsir's two-stage round. Boosts hard, then coasts on the sustainer.</summary>
    public static readonly MunitionProfile Missile57E6 = new()
    {
        Name = "57E6",
        DisplayName = "57E6 two-stage SAM",
        BodyMarker = "Missile",
    };

    // ---- Sensors --------------------------------------------------------

    public static readonly SensorProfile SearchRadar1Rs1 = new()
    {
        Name = "1RS1",
        DisplayName = "1RS1-1E search radar",
    };

    // ---- Launchers ------------------------------------------------------

    public static readonly LauncherProfile PantsirS1 = new()
    {
        PartId = "AirDefence_Prefab_Launcher6",
        DisplayName = "Pantsir-S1",
        Munition = "57E6",
        Sensor = "1RS1",

        TurretMarker = "Turret",
        PodsMarker = "Pods",
        RadarMarker = "Radar",

        // Generated: muzzle of each tube in the pods' frame, in firing order.
        TubeOffsets =
        [
            new( 2.95513,  1.79453,  1.33250),
            new( 2.95513,  1.79453, -1.33250),
            new( 2.95513,  1.79453,  1.10750),
            new( 2.95513,  1.79453, -1.10750),
            new( 2.82607,  1.97884,  1.33250),
            new( 2.82607,  1.97884, -1.33250),
            new( 2.82607,  1.97884,  1.10750),
            new( 2.82607,  1.97884, -1.10750),
            new( 2.69702,  2.16315,  1.33250),
            new( 2.69702,  2.16315, -1.33250),
            new( 2.69702,  2.16315,  1.10750),
            new( 2.69702,  2.16315, -1.10750),
        ],

        TurretPivot = new(0.00000, -1.42000, 0.00000),
        PodPivotFromTurret = new(2.62000, -0.63000, 0.00000),
        RadarPivotFromTurret = new(4.05000, -1.10000, 0.00000),
        PodReferenceElevationRad = 0.95993,          // 55 degrees
        MuzzleForwardOffset = 5.446,
        TubeRingRadius = 1.231,
    };

    // ---- Registry -------------------------------------------------------

    public static readonly IReadOnlyList<LauncherProfile> Launchers = [PantsirS1];
    public static readonly IReadOnlyList<MunitionProfile> Munitions = [Missile57E6];
    public static readonly IReadOnlyList<SensorProfile> Sensors = [SearchRadar1Rs1];

    /// <summary>The launcher matching a part Id, or null if that part is not one of ours.</summary>
    public static LauncherProfile? LauncherForPart(string? partId)
    {
        if (string.IsNullOrEmpty(partId)) return null;

        for (int i = 0; i < Launchers.Count; i++)
        {
            if (Launchers[i].PartId == partId) return Launchers[i];
        }
        return null;
    }

    /// <summary>
    /// The named munition. Falls back to the first registered rather than throwing: a launcher
    /// naming a round that does not exist is a typo in this file, and the game should still be
    /// playable while it is found.
    /// </summary>
    public static MunitionProfile MunitionNamed(string name) => Named(Munitions, name, m => m.Name);

    public static SensorProfile SensorNamed(string name) => Named(Sensors, name, s => s.Name);

    private static T Named<T>(IReadOnlyList<T> from, string name, Func<T, string> key)
    {
        for (int i = 0; i < from.Count; i++)
        {
            if (key(from[i]) == name) return from[i];
        }
        return from[0];
    }
}
