using Brutal.Numerics;

namespace KSArmory;

/// <summary>
/// Every weapon system the mod knows about.
///
/// <para><b>This is the file to add to.</b> A new launcher, round or sensor is an entry here
/// plus its art; no other C# needs to change. Discovery is by <see cref="LauncherProfile.PartId"/>,
/// so the battery picks up whatever is fitted without anything hardcoding a particular
/// vehicle.</para>
///
/// <para>The launcher geometry below is generated by <c>tools/model/pantsir.py</c> and checked
/// against the exported mesh by <c>tools/validate-parts.py</c>. Rerun the model build and paste
/// what it prints rather than editing the numbers.</para>
/// </summary>
public static class Arsenal
{
    // ---- Munitions ------------------------------------------------------

    /// <summary>57E6: the Pantsir's two-stage round. Boosts hard, then coasts on the sustainer.</summary>
    /// <summary>
    /// The 57E6, as flown by the real Pantsir-S1.
    ///
    /// <para>The defaults on <see cref="MunitionProfile"/> are this round, so the figures live
    /// there. What matters here is which of them are real and which are ours: peak speed
    /// (~1300 m/s), boost duration (~2.4 s), reach (20 km) and the command-link guidance are
    /// taken from the actual weapon. The fuse and blast radii are gameplay numbers — a 20 kg
    /// continuous-rod warhead has a much smaller lethal envelope than 20 m, but KSA exposes
    /// only binary destruction, so a realistic radius would read as the round doing nothing.</para>
    ///
    /// <para>The 57E6 carries <b>no seeker</b>. The vehicle tracks and uplinks steering commands,
    /// which is why a hard-manoeuvring target cannot blind it — the engagement ends when the
    /// launcher loses the track, not when the round loses sight of anything.</para>
    /// </summary>
    public static readonly MunitionProfile Missile57E6 = new()
    {
        Name = "57E6",
        DisplayName = "57E6 two-stage SAM",
        BodyMarker = "Missile",
        FinMarker = "Fins",
    };

    /// <summary>
    /// The 2A38M's 30 mm shell: the Pantsir's inner layer, for what the missiles cannot reach.
    ///
    /// <para>A <see cref="Slug"/> rather than an <see cref="Interceptor"/> — no seeker, no boost,
    /// no command link. It leaves at muzzle velocity and is then only ballistics and drag, which
    /// is why the numbers that matter here are speed and reach rather than guidance.</para>
    ///
    /// <para>Muzzle velocity (~960 m/s) and the 4 km effective range are the real weapon's. The
    /// fuse radii are ours: a 30 mm shell is a contact weapon, but the mod steps in sub-frames
    /// and cannot resolve a true contact, so the fuse is the smallest radius a round travelling
    /// 960 m/s can be tested against without stepping past it.</para>
    /// </summary>
    public static readonly MunitionProfile Cannon30Mm = new()
    {
        Name = "30MM",
        DisplayName = "2A38M 30 mm cannon",

        // No body subpart: twelve missile bodies exist because a salvo is twelve rounds, and a
        // burst is hundreds. Shells are drawn as tracers only.
        LaunchSpeed = 960f,
        BoostSeconds = 0f,
        BoostAccel = 0f,
        MaxFlightSeconds = 6f,

        // Heavier per frontal area than a missile, so it holds velocity better through the
        // thick air where it is used at all.
        DragK = 1.1e-5f,

        FuseRadius = 3f,
        FuseArmSeconds = 0.05f,
        LethalRadius = 4f,
        BlastRadius = 6f,
    };

    // ---- Sensors --------------------------------------------------------

    /// <summary>
    /// The 1RS1-1E search set, with the engagement envelope of the system it feeds.
    ///
    /// <para>Detection reaches much further than the round flies — 36 km against 20 km — so the
    /// envelope is a separate limit rather than a consequence of detection range. Without it the
    /// battery fires at everything it can see and the rounds expire short, which is precisely
    /// what every long crossing shot did.</para>
    /// </summary>
    public static readonly SensorProfile SearchRadar1Rs1 = new()
    {
        Name = "1RS1",
        DisplayName = "1RS1-1E search radar",
    };

    // ---- Launchers ------------------------------------------------------

    public static readonly LauncherProfile PantsirS1 = new()
    {
        PartId = "AirDefence_Prefab_Launcher6",
        DisplayName = "Pantsir-S1",
        Munition = "57E6",
        Sensor = "1RS1",

        TurretMarker = "Turret",
        PodsMarker = "Pods",
        RadarMarker = "Radar",
        GunsMarker = "Guns",
        OpticMarker = "Optic",

        // Generated: muzzle of each tube in the pods' frame, in firing order. The Pantsir's tubes
        // are a parallel block, so none declares a direction of its own and they all follow the
        // pods. tools/validate-parts.py checks these against the mesh.
        Tubes =
        [
            new( 2.95513,  1.79453,  1.33250),
            new( 2.95513,  1.79453, -1.33250),
            new( 2.95513,  1.79453,  1.10750),
            new( 2.95513,  1.79453, -1.10750),
            new( 2.82607,  1.97884,  1.33250),
            new( 2.82607,  1.97884, -1.33250),
            new( 2.82607,  1.97884,  1.10750),
            new( 2.82607,  1.97884, -1.10750),
            new( 2.69702,  2.16315,  1.33250),
            new( 2.69702,  2.16315, -1.33250),
            new( 2.69702,  2.16315,  1.10750),
            new( 2.69702,  2.16315, -1.10750),
        ],

        TurretPivot = new(0.00000, -1.42000, 0.00000),
        PodPivotFromTurret = new(2.62000, -0.63000, 0.00000),
        RadarPivotFromTurret = new(4.05000, -1.10000, 0.00000),
        OpticPivotFromTurret = new(4.10000, 1.07000, 0.44000),
        GunPivotFromTurret = new(3.70000, 0.07000, 0.00000),
        GunReferenceElevationRad = 0.38397,          // 22 degrees

        // The inner layer: what the missiles cannot reach, because they need 1.2 km to arm and
        // steer. Generated with the tube table by tools/model/pantsir.py.
        GunMunition = "30MM",
        GunMuzzles =
        [
            new( 1.01144,  2.50340, -1.94000),
            new( 1.01144,  2.50340, -1.76000),
            new( 1.01144,  2.50340,  1.76000),
            new( 1.01144,  2.50340,  1.94000),
        ],
        PodReferenceElevationRad = 0.95993,          // 55 degrees
        MuzzleForwardOffset = 5.446,
        TubeRingRadius = 1.231,
    };

    // ---- Registry -------------------------------------------------------

    public static readonly IReadOnlyList<LauncherProfile> Launchers = [PantsirS1];
    public static readonly IReadOnlyList<MunitionProfile> Munitions = [Missile57E6, Cannon30Mm];
    public static readonly IReadOnlyList<SensorProfile> Sensors = [SearchRadar1Rs1];

    /// <summary>
    /// The parts this mod recognises on a craft it did not design, keyed by part Id.
    ///
    /// <para>Separate from <see cref="Launchers"/>, which describes a whole weapon system as one
    /// prefab part with its geometry generated into this file. This describes *components*: what
    /// a player assembled, surveyed where they put it. A prefab appears in both, because the
    /// Pantsir is a launcher however it got onto the craft.</para>
    ///
    /// <para>Thin on purpose. Until there are parts to compose — a tube, a radar, a cannon, a
    /// manager — this registry has one entry and the survey has little to find. The mechanism is
    /// worth having first: it is what a second weapon system plugs into, and it is testable
    /// before any of that art exists.</para>
    /// </summary>
    public static readonly IReadOnlyList<ComponentProfile> Components =
    [
        new ComponentProfile
        {
            PartId = PantsirS1.PartId,
            Role = WeaponRole.Launcher,
            DisplayName = PantsirS1.DisplayName,

            // The Pantsir is one part. Its radar, optical head and cannon are subparts, so they
            // are declared rather than found -- see ComponentProfile.Provides.
            Provides =
            [
                new(WeaponRole.Sensor, SearchRadar1Rs1.DisplayName),
                new(WeaponRole.Camera, "Optical head"),
                new(WeaponRole.Gun, Cannon30Mm.DisplayName),
                new(WeaponRole.FireControl, "Pantsir-S1 fire control"),
            ],
        },
    ];

    /// <summary>The launcher matching a part Id, or null if that part is not one of ours.</summary>
    public static LauncherProfile? LauncherForPart(string? partId) => LauncherForPart(Launchers, partId);

    /// <summary>
    /// The same lookup against an explicit registry.
    ///
    /// <para>Exists so the selection logic can be tested with <em>several</em> launchers
    /// registered. With one entry every registry assertion is trivially satisfied and cannot
    /// distinguish "picks the right one" from "picks the only one" — and the mod ships with one
    /// launcher, so that is the state the suite would otherwise be stuck in forever.</para>
    /// </summary>
    internal static LauncherProfile? LauncherForPart(IReadOnlyList<LauncherProfile> from, string? partId)
    {
        if (string.IsNullOrEmpty(partId)) return null;

        for (int i = 0; i < from.Count; i++)
        {
            if (from[i].PartId == partId) return from[i];
        }
        return null;
    }

    /// <summary>
    /// The named munition. Falls back to the first registered rather than throwing: a launcher
    /// naming a round that does not exist is a typo in this file, and the game should still be
    /// playable while it is found.
    /// </summary>
    public static MunitionProfile MunitionNamed(string name) => Named(Munitions, name, m => m.Name);

    public static SensorProfile SensorNamed(string name) => Named(Sensors, name, s => s.Name);

    /// <summary>
    /// First entry whose key matches, or the first entry as a fallback. Internal rather than
    /// private so the fallback can be tested against a registry with more than one candidate,
    /// where "matched" and "fell back to element zero" are actually distinguishable.
    /// </summary>
    internal static T Named<T>(IReadOnlyList<T> from, string name, Func<T, string> key)
    {
        for (int i = 0; i < from.Count; i++)
        {
            if (key(from[i]) == name) return from[i];
        }
        return from[0];
    }
}
