using Brutal.Numerics;

namespace KSArmory;

/// <summary>
/// Every weapon system the mod knows about.
///
/// <para><b>This is the file to add to.</b> A new launcher, round or sensor is an entry here
/// plus its art; no other C# needs to change. Discovery is by <see cref="LauncherProfile.PartId"/>,
/// so the battery picks up whatever is fitted without anything hardcoding a particular
/// vehicle.</para>
///
/// <para>The launcher geometry below is generated by <c>tools/model/pantsir.py</c> and checked
/// against the exported mesh by <c>tools/validate-parts.py</c>. Rerun the model build and paste
/// what it prints rather than editing the numbers.</para>
/// </summary>
public static class Arsenal
{
    // ---- Munitions ------------------------------------------------------

    /// <summary>
    /// The 57E6, as flown by the real Pantsir-S1: a two-stage round that boosts hard and then
    /// coasts on the sustainer.
    ///
    /// <para>The defaults on <see cref="MunitionProfile"/> are this round, so the figures live
    /// there. What matters here is which of them are real and which are ours: peak speed
    /// (~1300 m/s), boost duration (~2.4 s), reach (20 km) and the command-link guidance are
    /// taken from the actual weapon. The fuse and blast radii are gameplay numbers — a 20 kg
    /// continuous-rod warhead has a much smaller lethal envelope than 20 m, but KSA exposes
    /// only binary destruction, so a realistic radius would read as the round doing nothing.</para>
    ///
    /// <para>The 57E6 carries <b>no seeker</b>. The vehicle tracks and uplinks steering commands,
    /// which is why a hard-manoeuvring target cannot blind it — the engagement ends when the
    /// launcher loses the track, not when the round loses sight of anything.</para>
    /// </summary>
    public static readonly MunitionProfile Missile57E6 = new()
    {
        MinRange = 1200f,
        MaxRange = 20000f,   // the 57E6's own reach

        Name = "57E6",
        DisplayName = "57E6 two-stage SAM",
        BodyMarker = "Missile",
        FinMarker = "Fins",
    };

    /// <summary>
    /// The 2A38M's 30 mm shell: the Pantsir's inner layer, for what the missiles cannot reach.
    ///
    /// <para>A <see cref="Slug"/> rather than an <see cref="Interceptor"/> — no seeker, no boost,
    /// no command link. It leaves at muzzle velocity and is then only ballistics and drag, which
    /// is why the numbers that matter here are speed and reach rather than guidance.</para>
    ///
    /// <para>Muzzle velocity (~960 m/s) and the 4 km effective range are the real weapon's. The
    /// fuse radii are ours: a 30 mm shell is a contact weapon, but the mod steps in sub-frames
    /// and cannot resolve a true contact, so the fuse is the smallest radius a round travelling
    /// 960 m/s can be tested against without stepping past it.</para>
    /// </summary>
    public static readonly MunitionProfile Cannon30Mm = new()
    {
        MinRange = 200f,
        MaxRange = 4000f,   // the 2A38M's effective reach

        Name = "30MM",
        DisplayName = "2A38M 30 mm cannon",

        // No body subpart: twelve missile bodies exist because a salvo is twelve rounds, and a
        // burst is hundreds. Shells are drawn as tracers only.
        LaunchSpeed = 960f,
        BoostSeconds = 0f,
        BoostAccel = 0f,
        MaxFlightSeconds = 6f,

        // Heavier per frontal area than a missile, so it holds velocity better through the
        // thick air where it is used at all.
        DragK = 1.1e-5f,

        FuseRadius = 3f,
        FuseArmSeconds = 0.05f,
        // Chosen to give the cannon a 4 m lethal radius. The same law then puts its blast radius
        // at about 12 m rather than the 6 m a hand-authored pair would use -- that one only
        // decides whether a near miss is logged, and one law cannot reproduce a pair authored at
        // a different ratio.
        ChargeKg = 0.16f,
    };

    /// <summary>
    /// The AIM-9J: a rail-launched infrared air-to-air missile.
    ///
    /// <para>Airframe figures are the real weapon's — 3.05 m, 127 mm, 78 kg, about Mach 2.5 off
    /// a five-second motor, reaching some 14 km. The seeker is what makes it a different round
    /// from the 57E6 rather than a smaller one: it homes on the target itself, so unlike a
    /// command-linked round it keeps guiding after the launcher loses the track — and it can be
    /// thrown off by a target that leaves its field of view.</para>
    ///
    /// <para>The warhead is the one number here that is not the real weapon's reach: 9.4 kg of
    /// blast-fragmentation gives a lethal envelope far smaller than the 15 m below, but KSA
    /// destroys or does nothing, so a truthful radius reads as the round missing.</para>
    /// </summary>
    public static readonly MunitionProfile Missile9J = new()
    {
        MinRange = 400f,
        MaxRange = 14000f,   // the AIM-9J's, which is what the rail throws

        Name = "AIM9J",
        DisplayName = "AIM-9J Sidewinder",
        BodyMarker = "Aim9",

        // No fin marker: a rail-launched round carries its fins deployed, so there is nothing
        // to unfold and no second subpart to scale.
        BodyLength = 3.05f,

        // Off the rail on its own motor rather than ejected: the launch speed is what the rail
        // imparts, which is nothing.
        LaunchSpeed = 25f,

        // Mk 17: a *booster*, not a sustainer. It burns for about 2.2 seconds and then the round
        // coasts the whole rest of the way, bleeding speed to drag — which is why a Sidewinder's
        // reach depends so heavily on how fast and how high it was launched, and why a long shot
        // arrives slow. A five-second burn would have it hold speed like a Pantsir round and read
        // as far too quick.
        //
        // The 2.2 s and the ~Mach 2.5 peak are the weapon's. The acceleration is those two
        // divided: the real motor's thrust is roughly constant while the missile sheds propellant,
        // so its acceleration climbs through the burn, and a flight model with no mass can only
        // take the average.
        BoostSeconds = 2.2f,
        BoostAccel = 370f,
        MaxFlightSeconds = 40f,

        // Lighter and finer than the 57E6, so it bleeds speed faster once the motor is out.
        DragK = 4.2e-5f,

        Guidance = GuidanceMode.Seeker,
        SeekerFovDeg = 40f,
        NavConstant = 4f,
        MaxLateralG = 30f,

        // Long enough to be clear of the rail and the craft before anything turns it — at a
        // standing start under 175 m/s^2 that is about 14 m.
        SeparationSeconds = 0.4f,

        FuseRadius = 12f,
        FuseArmSeconds = 1.0f,
        ChargeKg = 9.4f,
    };

    /// <summary>
    /// The M61A2's 20 mm round, as the Phalanx fires it.
    ///
    /// <para>Muzzle velocity (1100 m/s), the 1486 m effective range and the 4500 rpm the gun runs
    /// at are the real weapon's. What is ours is the fuse: a 20 mm round is a contact weapon and
    /// this mod steps in sub-frames, so the radius below is the smallest a round at 1100 m/s can
    /// be tested against without stepping straight past it.</para>
    ///
    /// <para>A far smaller charge than the Pantsir's shell, because it is a far smaller round —
    /// which through <see cref="Warhead"/> gives it about a third of the lethal radius. A CIWS
    /// makes up for that with volume.</para>
    /// </summary>
    public static readonly MunitionProfile Cannon20Mm = new()
    {
        MinRange = 100f,
        MaxRange = 1486f,   // the M61A2's, and the number the CIWS is built around

        Name = "20MM",
        DisplayName = "M61A2 20 mm",

        LaunchSpeed = 1100f,
        BoostSeconds = 0f,
        BoostAccel = 0f,

        // Just past the gun's own 1486 m reach, not four times it. At 1100 m/s five seconds is
        // 5.5 km of flight that can hit nothing, and at 75 rounds a second it keeps 375 shells in
        // the air to do it: every one stepped, drawn and logged.
        MaxFlightSeconds = 2f,

        DragK = 1.3e-5f,

        FuseRadius = 2.5f,
        FuseArmSeconds = 0.03f,
        ChargeKg = 0.05f,
    };

    // ---- Sensors --------------------------------------------------------

    /// <summary>
    /// A 500 lb general-purpose bomb: no seeker, no motor, no fuse but the ground.
    ///
    /// <para>Modelled on the Mk 82 — 227 kg all up, of which 87 kg is filler. The drag constant is
    /// set from its terminal velocity rather than guessed: a Mk 82 settles around 280 m/s, and
    /// <c>DragK = g / v²</c> is what makes it do that.</para>
    /// </summary>
    public static readonly MunitionProfile BombMk82 = new()
    {
        Name = "MK82",
        DisplayName = "Mk 82 500 lb bomb",
        BodyMarker = "Mk82",
        BodyLength = 2.22f,

        Guidance = GuidanceMode.None,

        // Released, not launched: what it mostly leaves with is the aircraft's velocity. The few
        // metres a second are the ejector cartridge, which throws a store down hard enough to
        // clear the airflow under the wing -- and at zero the launcher's EjectAwayFromMount is a
        // direction multiplied by nothing.
        LaunchSpeed = 4f,
        BoostSeconds = 0f,
        BoostAccel = 0f,

        MinRange = 0f,
        MaxRange = 20000f,

        // Long enough for a release from altitude: a drop from 10 km is about 45 seconds.
        MaxFlightSeconds = 120f,

        DragK = 1.25e-4f,

        // Contact. There is nothing to be near -- what it arrives at is the ground, and the hull
        // test decides a craft.
        FuseRadius = 0f,

        // Clear of the aircraft that dropped it before it can do anything. A bomb fused at release
        // is one that goes off under its own wing.
        FuseArmSeconds = 1.5f,

        ChargeKg = 87f,
        HitsTerrain = true,
    };

    /// <summary>
    /// The 1RS1-1E search set, with the engagement envelope of the system it feeds.
    ///
    /// <para>Detection reaches much further than the round flies — 36 km against 20 km — so the
    /// envelope is a separate limit rather than a consequence of detection range. Without it the
    /// battery fires at everything it can see and the rounds expire short of a long crossing
    /// target.</para>
    /// </summary>
    public static readonly SensorProfile SearchRadar1Rs1 = new()
    {
        Name = "1RS1",
        DisplayName = "1RS1-1E search radar",
    };

    /// <summary>
    /// The rail's own infrared search head: short-ranged, narrow, and pointed where the rail is.
    ///
    /// <para>Nothing on a Sidewinder rail rotates, so the volume it covers is decided entirely by
    /// how the part was mounted — <see cref="BoresightMode.PartForward"/> rather than local up,
    /// which would have a rail on a booster searching whichever way gravity happened to lie.</para>
    ///
    /// <para>Horizon masking is left on and the envelope is short: an IR seeker needs the target
    /// hot and roughly ahead, so this set finds things the Pantsir's radar would have swept up
    /// long before, and only within the arc the airframe is facing.</para>
    /// </summary>
    public static readonly SensorProfile SeekerHeadAim9 = new()
    {
        Name = "AIM9SEEK",
        DisplayName = "AIM-9 seeker head",

        Range = 16000f,
        ConeDeg = 50f,
        BoresightSource = BoresightMode.PartForward,

        ThreatRadius = 6000f,
        ThreatHorizonSeconds = 30f,
        LockSeconds = 1.0f,

        // Off the rail under its own power, so it needs far less room to arm than a round the
        // Pantsir ejects and then has to catch.
    };

    /// <summary>
    /// The Phalanx's own search and track set, in the radome above the gun.
    ///
    /// <para>Short and wide, which is the opposite of the Pantsir's set and the whole point of the
    /// weapon: a CIWS is the last layer, so it does not need to see far, it needs to see
    /// everything close and quickly. The engagement envelope is the gun's real reach — 1486 m
    /// effective — rather than anything the radar can manage.</para>
    /// </summary>
    public static readonly SensorProfile SearchRadarVps2 = new()
    {
        Name = "VPS2",
        DisplayName = "VPS-2 search and track",

        Range = 6000f,
        ConeDeg = 85f,

        ThreatRadius = 2500f,
        ThreatHorizonSeconds = 15f,
        LockSeconds = 0.6f,

    };

    // ---- Launchers ------------------------------------------------------

    /// <summary>
    /// The optical sight a bomb is released on. Not a radar and not a seeker: it exists so the
    /// system has something to draw and something to name what is ahead, because a rack that
    /// engages nothing by itself still has to tell the operator what it is over.
    /// </summary>
    public static readonly SensorProfile BombSight = new()
    {
        Name = "BOMBSIGHT",
        DisplayName = "Mk 9 bombsight",
        Range = 8000f,
        ConeDeg = 60f,
        BoresightSource = BoresightMode.PartForward,
        ThreatRadius = 3000f,
        ThreatHorizonSeconds = 20f,
        LockSeconds = 0.8f,
    };

    public static readonly LauncherProfile PantsirS1 = new()
    {
        PartId = "KSArmory_Prefab_Launcher6",
        DisplayName = "Pantsir-S1",
        Munition = "57E6",
        Sensor = "1RS1",

        TurretMarker = "Turret",
        PodsMarker = "Pods",
        RadarMarker = "Radar",
        GunsMarker = "Guns",
        OpticBaseMarker = "Launcher_OpticBase",

        // Generated: muzzle of each tube in the pods' frame, in firing order. The Pantsir's tubes
        // are a parallel block, so none declares a direction of its own and they all follow the
        // pods. tools/validate-parts.py checks these against the mesh.
        Tubes =
        [
            new( 2.95513,  1.79453,  1.33250),
            new( 2.95513,  1.79453, -1.33250),
            new( 2.95513,  1.79453,  1.10750),
            new( 2.95513,  1.79453, -1.10750),
            new( 2.82607,  1.97884,  1.33250),
            new( 2.82607,  1.97884, -1.33250),
            new( 2.82607,  1.97884,  1.10750),
            new( 2.82607,  1.97884, -1.10750),
            new( 2.69702,  2.16315,  1.33250),
            new( 2.69702,  2.16315, -1.33250),
            new( 2.69702,  2.16315,  1.10750),
            new( 2.69702,  2.16315, -1.10750),
        ],

        TurretPivot = new(0.00000, -1.42000, 0.00000),
        PodPivotFromTurret = new(2.62000, -0.63000, 0.00000),
        RadarPivotFromTurret = new(4.05000, -1.10000, 0.00000),
        OpticBaseFromTurret = new(3.46000, 0.82000, 0.44000),
        GunPivotFromTurret = new(3.70000, 0.07000, 0.00000),
        GunReferenceElevationRad = 0.38397,          // 22 degrees

        // The inner layer: what the missiles cannot reach, because they need 1.2 km to arm and
        // steer. Generated with the tube table by tools/model/pantsir.py.
        GunMunition = "30MM",
        GunMuzzles =
        [
            new( 1.01144,  2.50340, -1.94000),
            new( 1.01144,  2.50340, -1.76000),
            new( 1.01144,  2.50340,  1.76000),
            new( 1.01144,  2.50340,  1.94000),
        ],
        PodReferenceElevationRad = 0.95993,          // 55 degrees
        MuzzleForwardOffset = 5.446,
        TubeRingRadius = 1.231,
    };

    /// <summary>
    /// A single LAU-7 launch rail carrying one AIM-9J, attached to the side of whatever it is
    /// bolted to.
    ///
    /// <para>The other shape a launcher takes: nothing on it moves. No turret marker and no pods
    /// marker, so <see cref="LauncherProfile.Trains"/> is false, the drives are skipped and the
    /// launcher counts as laid from the moment it exists — fire control cannot deadlock waiting
    /// for gear that will never turn. Where it can shoot is decided by how the craft is pointed,
    /// which is the trade for it being a rail rather than a vehicle.</para>
    ///
    /// <para>One tube and no reload, so a craft carrying this has exactly one shot. Fitting a
    /// second rail does <em>not</em> give it two: a battery runs the launcher at
    /// <c>LauncherOrdinal</c>, which is pinned to the first, and the roster crews one battery per
    /// craft. Unpinning that is the next step and is tracked in <c>docs/MODULARITY.md</c>.</para>
    ///
    /// <para>Geometry generated by <c>tools/model/sidewinder.py</c> and checked against the
    /// exported mesh by <c>tools/validate-parts.py</c>.</para>
    /// </summary>
    public static readonly LauncherProfile SidewinderRail = new()
    {
        PartId = "KSArmory_Prefab_SidewinderRail",
        DisplayName = "LAU-7 Sidewinder rail",
        Munition = "AIM9J",
        Sensor = "AIM9SEEK",

        // The nose of the seated round and the direction it leaves along. A fixed launcher has no
        // pods for its tubes to follow, so unlike the Pantsir's parallel bundle this one has to
        // declare its own axis.
        Tubes = [new(new(0.40850, 1.52500, 0.00000), new(0, 1, 0))],
        MuzzleForwardOffset = 0.408,

        // Off the rail, then a turn.
        //
        // The round leaves along the rail and pushed clear of the mount, coasts for
        // MunitionProfile.SeparationSeconds so it is out of the craft's way, and only then steers.
        // The arc that produces is bounded by the round's own lateral G, which is what stops it
        // pivoting on the spot the way an immediate turn does.
        //
        // A rail on a stack points wherever the stack does, so it cannot be aimed by pointing the
        // craft: a ground designation sits 92-116 degrees off the rail. That is a limit on the
        // *seeker*, not on the weapon — a designated place is held by the operator, so it is
        // steered onto regardless of where the round is looking. See Interceptor's SeekerInView
        // and FireGate.CanGuideOntoAimpoint.
        LaunchAlongTube = true,
        EjectAwayFromMount = 0.55f,
        LaunchLoft = 0f,
        MuzzleOffset = 2f,

        // A rail holds what it holds. Zero means the magazine is never refilled, so the round
        // count in the panel is the number of rails fitted.
        ReloadSeconds = 0f,
        SettleSeconds = 0f,
    };

    /// <summary>
    /// A 14-inch ejector rack carrying one Mk 82. Nothing on it moves and nothing about it aims:
    /// the aircraft is the launcher, and the operator's judgement is the fire control.
    ///
    /// <para>Geometry pasted from <c>tools/model/bombrack.py</c>, which prints it. Change the rack
    /// there, rerun <c>tools/model/build.sh</c>, paste the block — <c>validate-parts.py</c> fails
    /// if the two ever disagree.</para>
    /// </summary>
    public static readonly LauncherProfile BombRack = new()
    {
        PartId = "KSArmory_Prefab_BombRack",
        DisplayName = "Mk 82 bomb rack",
        Munition = "MK82",
        Sensor = "BOMBSIGHT",
        Tubes = [new(new(0.40650, 1.11000, 0.00000), new(0, 1, 0))],
        MuzzleForwardOffset = 0.407,
        LaunchAlongTube = true,

        // Enough to clear the rack and the wing before gravity takes it. A real ejector cartridge
        // throws a store down hard for exactly this reason.
        EjectAwayFromMount = 1.2f,

        LaunchLoft = 0f,
        MuzzleOffset = 2f,
        ReloadSeconds = 0f,
        SettleSeconds = 0f,
    };

    /// <summary>
    /// Mk 15 Phalanx: a gun and nothing else, on a 3 m stack node.
    ///
    /// <para><b>The one launcher here that carries no missiles at all.</b> <c>Tubes</c> is empty,
    /// so <see cref="LauncherProfile.TubeCount"/> is zero and the magazine holds nothing — every
    /// path that reaches for a round has to cope with there being none.</para>
    ///
    /// <para>It still trains: the housing traverses and the barrels elevate, so
    /// <see cref="LauncherProfile.Trains"/> is true and fire control waits for it to settle. What
    /// it has no pods marker for is a launcher assembly, because there is not one.</para>
    ///
    /// <para>Traverse and elevation limits are the real mount's. Geometry generated by
    /// <c>tools/model/ciws.py</c>.</para>
    /// </summary>
    public static readonly LauncherProfile Ciws = new()
    {
        PartId = "KSArmory_Prefab_Ciws",
        DisplayName = "Mk 15 Phalanx",
        Munition = "20MM",
        Sensor = "VPS2",

        TurretMarker = "Ciws_Turret",
        GunsMarker = "Ciws_Guns",

        // No missiles. The gun is the weapon.
        Tubes = [],

        TurretPivot = new(0.10000, 0.00000, 0.00000),
        GunPivotFromTurret = new(2.20000, 0.00000, 0.00000),
        GunReferenceElevationRad = 0.0,           // level: the pose it fights sea-skimmers in

        GunMunition = "20MM",
        GunMuzzles =
        [
            new(-0.19500, 1.98000,  0.00000),
            new(-0.24750, 1.98000,  0.09093),
            new(-0.35250, 1.98000,  0.09093),
            new(-0.40500, 1.98000,  0.00000),
            new(-0.35250, 1.98000, -0.09093),
            new(-0.24750, 1.98000, -0.09093),
        ],

        // The real mount: 150 degrees either side of the centreline, and -25 to +85 in elevation.
        SlewRateDeg = 100f,
        ElevationRateDeg = 86f,
        MinElevationDeg = -25f,
        MaxElevationDeg = 85f,
        ForwardMinElevationDeg = -25f,
        SettleSeconds = 0.2f,

        // 4500 rpm, and 1550 rounds. Long bursts, because that is what a CIWS does.
        GunAmmo = 1550,
        GunRoundsPerMinute = 4500f,
        GunBurstRounds = 60,
        GunBurstGapSeconds = 0.35f,
        GunReloadSeconds = 0f,

        // No missile magazine to refill. Left at the profile's 12 s default the
        // battery reloads forever, because a magazine with no tubes is always empty.
        ReloadSeconds = 0f,
    };

    /// <summary>
    /// The EO director's own sensor. Narrow and short-ranged next to a search radar, because it
    /// is a telescope rather than a set: it sees what it is pointed at, in detail, and finds
    /// nothing on its own beyond a few kilometres.
    ///
    /// <para><see cref="BoresightMode.PartForward"/>, so its volume follows the craft's attitude
    /// rather than pointing at the sky — a director bolted to the side of a hull looks out of
    /// that side.</para>
    /// </summary>
    public static readonly SensorProfile EoSensor = new()
    {
        Name = "EO",
        DisplayName = "EO director",
        Range = 12000f,
        ConeDeg = 75f,
        BoresightSource = BoresightMode.PartForward,
        ThreatRadius = 4000f,
        ThreatHorizonSeconds = 30f,
        LockSeconds = 0.6f,

        // It watches rather than engages, so it has no reason to ignore something slow. A search
        // set does, because a docked craft is not a threat; a sight pointed at one is doing its
        // job.
        MinTargetSpeed = 0f,
    };

    /// <summary>
    /// A standalone electro-optical director. Geometry from <c>tools/model/optic.py</c>.
    /// </summary>
    public static readonly OpticProfile EoDirector = new()
    {
        PartId = "KSArmory_Prefab_Optic",
        DisplayName = "EO Director",
        Sensor = EoSensor.Name,

        BaseMarker = "Optic_Base",
        HeadMarker = "Optic_Head",

        HeadPivot = new(0.63000, 0.00000, 0.00000),
        EyeForward = 0.300f,
        MinElevationDeg = -20f,
        MaxElevationDeg = 85f,
    };

    /// <summary>
    /// The Pantsir's own director, on its turret roof.
    ///
    /// <para>The same instrument as <see cref="EoDirector"/> — same bodies, same sensor, same
    /// travel — differing only in which part carries it and which subparts are its own. A second
    /// <c>OpticProfile</c> rather than a flag on the launcher, because that is what makes it a
    /// director at all: <c>OpticParts</c> finds it, <c>OpticalHead</c> crews it, and the sight, the
    /// chase camera and the claim ladder never learn that this one sits on a weapon.</para>
    ///
    /// <para><see cref="OpticProfile.HeadPivot"/> is identical to the standalone's because it is an
    /// offset from the <em>base</em> rather than a point in the part. Where the base has got to is
    /// read off the engine each frame — see <see cref="MountFrame"/> — which is why riding a
    /// traverse needs nothing here at all.</para>
    /// </summary>
    public static readonly OpticProfile PantsirDirector = new()
    {
        PartId = "KSArmory_Prefab_Launcher6",
        DisplayName = "1TPP1 director",
        Sensor = EoSensor.Name,

        BaseMarker = "Launcher_OpticBase",
        HeadMarker = "Launcher_OpticHead",

        HeadPivot = new(0.63000, 0.00000, 0.00000),
        EyeForward = 0.300f,
        MinElevationDeg = -20f,
        MaxElevationDeg = 85f,
    };

    // ---- Registry -------------------------------------------------------

    public static readonly IReadOnlyList<LauncherProfile> Launchers = [PantsirS1, SidewinderRail, Ciws, BombRack];
    public static readonly IReadOnlyList<MunitionProfile> Munitions =
        [Missile57E6, Cannon30Mm, Missile9J, Cannon20Mm, BombMk82];
    public static readonly IReadOnlyList<SensorProfile> Sensors =
        [SearchRadar1Rs1, SeekerHeadAim9, SearchRadarVps2, BombSight, EoSensor];

    /// <summary>
    /// Optical heads. Most are parts in their own right; one rides a launcher's turret, and
    /// nothing downstream can tell which is which.
    /// </summary>
    public static readonly IReadOnlyList<OpticProfile> Optics = [EoDirector, PantsirDirector];

    /// <summary>
    /// The parts this mod recognises on a craft it did not design, keyed by part Id.
    ///
    /// <para>Separate from <see cref="Launchers"/>, which describes a whole weapon system as one
    /// prefab part with its geometry generated into this file. This describes *components*: what
    /// a player assembled, surveyed where they put it. A prefab appears in both, because the
    /// Pantsir is a launcher however it got onto the craft.</para>
    ///
    /// <para>Thin on purpose. Until there are parts to compose — a tube, a radar, a cannon, a
    /// manager — this registry has one entry and the survey has little to find. The mechanism is
    /// worth having first: it is what a second weapon system plugs into, and it is testable
    /// before any of that art exists.</para>
    /// </summary>
    public static readonly IReadOnlyList<ComponentProfile> Components =
    [
        new ComponentProfile
        {
            PartId = PantsirS1.PartId,
            Role = WeaponRole.Launcher,
            DisplayName = PantsirS1.DisplayName,

            // The Pantsir is one part. Its radar, optical head and cannon are subparts, so they
            // are declared rather than found -- see ComponentProfile.Provides.
            Provides =
            [
                new(WeaponRole.Sensor, SearchRadar1Rs1.DisplayName),
                new(WeaponRole.Gun, Cannon30Mm.DisplayName),
                new(WeaponRole.FireControl, "Pantsir-S1 fire control"),

                // The director on its turret roof, which is subpart gear rather than a part a
                // survey could find on its own -- exactly what Provides is for.
                new(WeaponRole.Camera, PantsirDirector.DisplayName),
            ],
        },
        new ComponentProfile
        {
            PartId = EoDirector.PartId,
            Role = WeaponRole.Camera,
            DisplayName = EoDirector.DisplayName,

            // Nothing declared, and that is the whole point of the distinction. Provides exists
            // for a prefab whose gear is subparts the survey cannot see -- the Pantsir's search
            // radar above. A director's sensor is not gear it carries, it *is* the director, and
            // the survey walks parts and finds it directly. Declaring one anyway minted a second
            // row for one object, filed under Sensors, with no control on it and nothing to say
            // but that there was no weapons system to belong to.
        },
        new ComponentProfile
        {
            PartId = SidewinderRail.PartId,
            Role = WeaponRole.Launcher,
            DisplayName = SidewinderRail.DisplayName,

            // The seeker head is the round's, not the rail's, but the rail is what a survey can
            // see and what the battery searches with -- so this is where it is declared.
            Provides =
            [
                new(WeaponRole.Sensor, SeekerHeadAim9.DisplayName),
                new(WeaponRole.FireControl, "LAU-7 fire control"),
            ],
        },
        new ComponentProfile
        {
            PartId = Ciws.PartId,
            Role = WeaponRole.Launcher,
            DisplayName = Ciws.DisplayName,
            Provides =
            [
                new(WeaponRole.Sensor, SearchRadarVps2.DisplayName),
                new(WeaponRole.Gun, Cannon20Mm.DisplayName),
                new(WeaponRole.FireControl, "Mk 15 fire control"),
            ],
        },
        new ComponentProfile
        {
            PartId = BombRack.PartId,
            Role = WeaponRole.Launcher,
            DisplayName = BombRack.DisplayName,

            // The sight is the crew's rather than the rack's, but the rack is what a survey can
            // see -- the same reasoning as the rail's seeker head above.
            Provides =
            [
                new(WeaponRole.Sensor, BombSight.DisplayName),
                new(WeaponRole.FireControl, "Mk 82 release"),
            ],
        },
    ];

    /// <summary>The launcher matching a part Id, or null if that part is not one of ours.</summary>
    public static LauncherProfile? LauncherForPart(string? partId) => LauncherForPart(Launchers, partId);

    /// <summary>The optical head a part Id names, or null if it names none.</summary>
    public static OpticProfile? OpticForPart(string? partId)
    {
        if (string.IsNullOrEmpty(partId)) return null;

        for (int i = 0; i < Optics.Count; i++)
        {
            if (Optics[i].PartId == partId) return Optics[i];
        }

        return null;
    }

    /// <summary>
    /// The same lookup against an explicit registry.
    ///
    /// <para>Exists so the selection logic can be tested against a registry of any size. With one
    /// entry every registry assertion is trivially satisfied and cannot distinguish "picks the
    /// right one" from "picks the only one".</para>
    /// </summary>
    internal static LauncherProfile? LauncherForPart(IReadOnlyList<LauncherProfile> from, string? partId)
    {
        if (string.IsNullOrEmpty(partId)) return null;

        for (int i = 0; i < from.Count; i++)
        {
            if (from[i].PartId == partId) return from[i];
        }
        return null;
    }

    /// <summary>
    /// The named munition. Falls back to the first registered rather than throwing: a launcher
    /// naming a round that does not exist is a typo in this file, and the game should still be
    /// playable while it is found.
    /// </summary>
    public static MunitionProfile MunitionNamed(string name) => Named(Munitions, name, m => m.Name);

    public static SensorProfile SensorNamed(string name) => Named(Sensors, name, s => s.Name);

    /// <summary>
    /// The round and sensor a launcher names, resolved together.
    ///
    /// <para>Together because a launcher left holding another system's round is a wrong-weapon
    /// bug with nothing on screen to show for it. Every caller that adopts a launcher takes all
    /// three, and this is the one place that pairing is made.</para>
    /// </summary>
    public static (MunitionProfile Munition, SensorProfile Sensor) LoadoutFor(LauncherProfile launcher)
        => LoadoutFor(launcher, Munitions, Sensors);

    /// <summary>
    /// The same pairing against explicit registries, so switching between systems is testable
    /// with several of each registered.
    /// </summary>
    internal static (MunitionProfile Munition, SensorProfile Sensor) LoadoutFor(
        LauncherProfile launcher,
        IReadOnlyList<MunitionProfile> munitions,
        IReadOnlyList<SensorProfile> sensors)
        => (Named(munitions, launcher.Munition, m => m.Name),
            Named(sensors, launcher.Sensor, s => s.Name));

    /// <summary>
    /// First entry whose key matches, or the first entry as a fallback. Internal rather than
    /// private so the fallback can be tested against a registry with more than one candidate,
    /// where "matched" and "fell back to element zero" are actually distinguishable.
    /// </summary>
    internal static T Named<T>(IReadOnlyList<T> from, string name, Func<T, string> key)
    {
        for (int i = 0; i < from.Count; i++)
        {
            if (key(from[i]) == name) return from[i];
        }
        return from[0];
    }
}
