using Brutal.Numerics;

namespace KSArmory;

/// <summary>
/// One tube: where its mouth is, and optionally which way it points.
///
/// <para><see cref="Direction"/> is in the same frame as <see cref="Position"/> — the pod's, or the
/// launcher part's for a launcher with no pods. <b>Zero means "share the pod axis"</b>, which is
/// what a launcher with parallel tubes wants and what the model generator emits, so the common case
/// stays a bare position.</para>
///
/// <para>A per-tube direction is what a splayed bundle needs — a VLS with divergence, an MLRS, or
/// anything whose tubes are not a parallel block.</para>
/// </summary>
public readonly record struct Tube(double3 Position, double3 Direction)
{
    /// <summary>A tube that points wherever the pods do. This is the generated form.</summary>
    public Tube(double x, double y, double z) : this(new double3(x, y, z), default) { }

    /// <summary>False when this tube simply follows the pod axis.</summary>
    public bool HasOwnDirection => !Direction.Equals(default(double3));
}

/// <summary>
/// One launch platform: which part it is, where its tubes are, what moves, and what it fires.
///
/// <para>This is the file a new weapon system is added to. Nothing in the simulation or the
/// KSA binding knows about the Pantsir specifically — they ask a profile. A fixed launcher with
/// no turret is the same type with <see cref="TurretMarker"/> left null.</para>
///
/// <para>The geometry here is generated by <c>tools/model/pantsir.py</c> and checked against
/// the mesh by <c>tools/validate-parts.py</c>. Do not hand-edit it.</para>
/// </summary>
public sealed class LauncherProfile
{
    /// <summary>Part Id declared in the mod's GameData XML. Must match exactly.</summary>
    public required string PartId { get; init; }

    public required string DisplayName { get; init; }

    /// <summary>Registry keys for what this launcher shoots and what it sees with.</summary>
    public required string Munition { get; init; }
    public required string Sensor { get; init; }

    // ---- Subparts the mod animates. Null means this system has no such piece. ----

    /// <summary>Traverses in azimuth. Null for a launcher that cannot train.</summary>
    public string? TurretMarker { get; init; }

    /// <summary>Elevates on the turret's trunnions, and carries the tubes.</summary>
    public string? PodsMarker { get; init; }

    /// <summary>Turns continuously. Cosmetic.</summary>
    public string? RadarMarker { get; init; }

    /// <summary>Cannon that elevate on their own trunnion. Null for a launcher with none.</summary>
    public string? GunsMarker { get; init; }

    // ---- Geometry, generated. See the class summary. ----

    /// <summary>Rounds carried, and the length of <see cref="Tubes"/>.</summary>
    public int TubeCount => Tubes.Length;

    /// <summary>
    /// Every tube in firing order, in the frame of whichever subpart carries them — the pods if
    /// there are any, otherwise the launcher part itself.
    ///
    /// <para>Positions here are generated by <c>tools/model/pantsir.py</c> and checked against the
    /// exported mesh by <c>tools/validate-parts.py</c>. Directions are not: the generator only
    /// knows parallel tubes, so a splayed launcher declares them by hand.</para>
    /// </summary>
    public required Tube[] Tubes { get; init; }

    /// <summary>Where the turret's traverse axis sits in the part's frame.</summary>
    public double3 TurretPivot { get; init; }

    /// <summary>Where the pods' trunnion sits relative to the turret's axis.</summary>
    public double3 PodPivotFromTurret { get; init; }

    /// <summary>Where the search array's turntable sits relative to the turret's axis.</summary>
    public double3 RadarPivotFromTurret { get; init; }

    /// <summary>Where the cannon trunnion sits relative to the turret's axis.</summary>
    public double3 GunPivotFromTurret { get; init; }

    /// <summary>
    /// Elevation the cannon are modelled at. Runtime elevation is a rotation away from it, the
    /// same convention as <see cref="PodReferenceElevationRad"/>.
    /// </summary>
    public double GunReferenceElevationRad { get; init; }

    /// <summary>
    /// Elevation the pods are modelled at. Runtime elevation is a rotation <em>away</em> from it,
    /// so a refused transform write leaves the vehicle in a pose that looks right.
    /// </summary>
    public double PodReferenceElevationRad { get; init; }

    /// <summary>Distance from the part origin to the tube muzzles along the boresight (m).</summary>
    public double MuzzleForwardOffset { get; init; }

    /// <summary>
    /// Radius of the ring the *fallback* launch positions are spread on (m), used only when
    /// the tube-carrying subpart cannot be resolved.
    /// </summary>
    public double TubeRingRadius { get; init; }

    // ---- Drives ---------------------------------------------------------

    public float SlewRateDeg = 70f;
    public float ElevationRateDeg = 45f;
    public float SettleSeconds = 0.35f;
    public float SearchRadarRpm = 20f;

    /// <summary>Elevation travel, and the higher floor over the vehicle's own bodywork.</summary>
    public float MinElevationDeg;
    public float MaxElevationDeg = 82f;
    public float ForwardMinElevationDeg = 15f;
    public float ForwardArcDeg = 50f;

    // ---- Firing ---------------------------------------------------------

    /// <summary>
    /// Rounds carried in total. Zero means one per tube, which is what a missile launcher wants.
    ///
    /// <para>A gun sets this far above <see cref="TubeCount"/>: one or two barrels and a belt of
    /// hundreds. Tubes then cycle rather than empty, and only the reserve runs down.</para>
    /// </summary>
    public int MagazineDepth;

    /// <summary>Seconds between consecutive rounds of a salvo.</summary>
    public float SalvoSpacing = 0.45f;

    /// <summary>Seconds to reload an empty launcher. Zero disables auto-reload.</summary>
    public float ReloadSeconds = 12f;

    /// <summary>
    /// Eject along the tube rather than slewing onto the target at launch. Only sensible for a
    /// launcher that aims; a fixed one has to slew, and wants <see cref="LaunchLoft"/>.
    /// </summary>
    public bool LaunchAlongTube = true;

    /// <summary>Bias toward the boresight for launchers that cannot aim. See FireGeometry.</summary>
    public float LaunchLoft = 0.35f;

    /// <summary>Standoff used when no launcher part is fitted at all (m).</summary>
    public float MuzzleOffset = 8f;

    /// <summary>Turret drive rates in the units the drive wants.</summary>
    public double SlewRateRad => float.DegreesToRadians(SlewRateDeg);
    public double ElevationRateRad => float.DegreesToRadians(ElevationRateDeg);

    /// <summary>Applies this profile's travel limits to a drive.</summary>
    public void ConfigureTurret(Turret turret)
    {
        turret.MinElevationRad = float.DegreesToRadians(MinElevationDeg);
        turret.MaxElevationRad = float.DegreesToRadians(MaxElevationDeg);
        turret.ForwardMinElevationRad = float.DegreesToRadians(ForwardMinElevationDeg);
        turret.ForwardArcRad = float.DegreesToRadians(ForwardArcDeg);
    }
}
