using Brutal.Numerics;

namespace KSArmory;

/// <summary>
/// One tube: where its mouth is, and optionally which way it points.
///
/// <para><see cref="Direction"/> is in the same frame as <see cref="Position"/> — the pod's, or the
/// launcher part's for a launcher with no pods. <b>Zero means "share the pod axis"</b>, which is
/// what a launcher with parallel tubes wants and what the model generator emits, so the common case
/// stays a bare position.</para>
///
/// <para>A per-tube direction is what a splayed bundle needs — a VLS with divergence, an MLRS, or
/// anything whose tubes are not a parallel block.</para>
/// </summary>
public readonly record struct Tube(double3 Position, double3 Direction)
{
    /// <summary>A tube that points wherever the pods do. This is the generated form.</summary>
    public Tube(double x, double y, double z) : this(new double3(x, y, z), default) { }

    /// <summary>False when this tube simply follows the pod axis.</summary>
    public bool HasOwnDirection => !Direction.Equals(default(double3));
}

/// <summary>
/// One launch platform: which part it is, where its tubes are, what moves, and what it fires.
///
/// <para>This is the file a new weapon system is added to. Nothing in the simulation or the
/// KSA binding knows about the Pantsir specifically — they ask a profile. A fixed launcher with
/// no turret is the same type with <see cref="TurretMarker"/> left null.</para>
///
/// <para>The geometry here is generated by <c>tools/model/pantsir.py</c> and checked against
/// the mesh by <c>tools/validate-parts.py</c>. Do not hand-edit it.</para>
/// </summary>
public sealed class LauncherProfile
{
    /// <summary>
    /// What a weapons system is running before it has found its launcher part.
    ///
    /// <para>Deliberately not the first registered launcher: seeding from one makes an unadopted
    /// system claim that weapon's reach and that weapon's radar, and makes an empty registry a
    /// type-initialiser crash rather than a quiet nothing. <see cref="PartId"/> is blank, so no
    /// lookup can return it.</para>
    /// </summary>
    public static readonly LauncherProfile Unfitted = new()
    {
        PartId = "",
        DisplayName = "no launcher",
        Munition = "",
        Sensor = "",
        Tubes = [],
    };

    /// <summary>Part Id declared in the mod's GameData XML. Must match exactly.</summary>
    public required string PartId { get; init; }

    public required string DisplayName { get; init; }

    /// <summary>Registry keys for what this launcher shoots and what it sees with.</summary>
    public required string Munition { get; init; }
    public required string Sensor { get; init; }

    /// <summary>
    /// What each armament is called in front of an operator. These name the status row, the
    /// switch that lets the armament engage and its tuning section, so a launcher that lobs
    /// bombs says "Bombs" everywhere without the panel knowing what a bomb is.
    /// </summary>
    public string TubeArmamentLabel { get; init; } = "Missiles";

    /// <inheritdoc cref="TubeArmamentLabel"/>
    public string GunArmamentLabel { get; init; } = "Cannon";

    // ---- Subparts the mod animates. Null means this system has no such piece. ----

    /// <summary>Traverses in azimuth. Null for a launcher that cannot train.</summary>
    public string? TurretMarker { get; init; }

    /// <summary>Elevates on the turret's trunnions, and carries the tubes.</summary>
    public string? PodsMarker { get; init; }

    /// <summary>Turns continuously. Cosmetic.</summary>
    public string? RadarMarker { get; init; }

    /// <summary>Cannon that elevate on their own trunnion. Null for a launcher with none.</summary>
    public string? GunsMarker { get; init; }

    /// <summary>
    /// An optical director's base, riding the traverse. Null for a launcher carrying none, which
    /// is most of them.
    ///
    /// <para>The launcher's only interest in a director is <em>carrying</em> it: this is here so
    /// the traverse writes the base's transform along with everything else that rides it. What the
    /// head then does is none of the launcher's business — it reads where its base ended up and
    /// aims itself, through its own <c>OpticProfile</c>. See <see cref="OpticGeometry.MountFrame"/>
    /// for why that direction of dependency is the one that generalises.</para>
    /// </summary>
    public string? OpticBaseMarker { get; init; }

    // ---- Geometry, generated. See the class summary. ----

    /// <summary>Rounds carried, and the length of <see cref="Tubes"/>.</summary>
    public int TubeCount => Tubes.Length;

    /// <summary>
    /// Every tube in firing order, in the frame of whichever subpart carries them — the pods if
    /// there are any, otherwise the launcher part itself.
    ///
    /// <para>Positions here are generated by <c>tools/model/pantsir.py</c> and checked against the
    /// exported mesh by <c>tools/validate-parts.py</c>. Directions are not: the generator only
    /// knows parallel tubes, so a splayed launcher declares them by hand.</para>
    /// </summary>
    public required Tube[] Tubes { get; init; }

    /// <summary>Where the turret's traverse axis sits in the part's frame.</summary>
    public double3 TurretPivot { get; init; }

    /// <summary>Where the pods' trunnion sits relative to the turret's axis.</summary>
    public double3 PodPivotFromTurret { get; init; }

    /// <summary>Where the search array's turntable sits relative to the turret's axis.</summary>
    public double3 RadarPivotFromTurret { get; init; }

    /// <summary>Where a carried director's base sits relative to the turret's axis.</summary>
    public double3 OpticBaseFromTurret { get; init; }

    /// <summary>Where the cannon trunnion sits relative to the turret's axis.</summary>
    public double3 GunPivotFromTurret { get; init; }

    /// <summary>
    /// Elevation the cannon are modelled at. Runtime elevation is a rotation away from it, the
    /// same convention as <see cref="PodReferenceElevationRad"/>.
    /// </summary>
    public double GunReferenceElevationRad { get; init; }

    /// <summary>
    /// Elevation the pods are modelled at. Runtime elevation is a rotation <em>away</em> from it,
    /// so a refused transform write leaves the vehicle in a pose that looks right.
    /// </summary>
    public double PodReferenceElevationRad { get; init; }

    /// <summary>Distance from the part origin to the tube muzzles along the boresight (m).</summary>
    public double MuzzleForwardOffset { get; init; }

    /// <summary>
    /// Radius of the ring the *fallback* launch positions are spread on (m), used only when
    /// the tube-carrying subpart cannot be resolved.
    /// </summary>
    public double TubeRingRadius { get; init; }

    // ---- Drives ---------------------------------------------------------

    public float SlewRateDeg = 70f;
    public float ElevationRateDeg = 45f;
    public float SettleSeconds = 0.35f;
    public float SearchRadarRpm = 20f;

    /// <summary>
    /// How many faces of the search array radiate, and therefore how many sweeps a scope draws.
    ///
    /// <para>One for an ordinary single-face set. The Pantsir's array is a double-sided wedge, so
    /// both of its faces are looking at once and the scope shows two traces half a turn apart —
    /// which is why its picture refreshes twice per revolution rather than once.</para>
    ///
    /// <para>A count rather than a flag, so a three- or four-face set needs no new concept. Zero or
    /// less means a set with no rotating array at all, and draws no sweep.</para>
    /// </summary>
    public int SearchRadarFaces = 1;

    /// <summary>Elevation travel, and the higher floor over the vehicle's own bodywork.</summary>
    public float MinElevationDeg;
    public float MaxElevationDeg = 82f;
    public float ForwardMinElevationDeg = 15f;
    public float ForwardArcDeg = 80f;
    public float ForwardPlateauDeg = 62f;

    /// <summary>
    /// Elevation the launcher returns to with nothing to look at. Defaults to the pods' modelled
    /// pose, so a stowed launcher sits where its mesh was built and a refused write is invisible.
    /// </summary>
    public double RestElevationRad => double.IsFinite(RestElevationDeg)
        ? double.DegreesToRadians(RestElevationDeg)
        : PodReferenceElevationRad;

    /// <summary>NaN follows <see cref="PodReferenceElevationRad"/>; set it to override.</summary>
    public float RestElevationDeg = float.NaN;

    /// <summary>True when something has to be aimed before this launcher can shoot.</summary>
    public bool Trains => TurretMarker is not null || PodsMarker is not null;

    // ---- Firing ---------------------------------------------------------

    /// <summary>
    /// Rounds carried in total. Zero means one per tube, which is what a missile launcher wants.
    ///
    /// <para>A gun sets this far above <see cref="TubeCount"/>: one or two barrels and a belt of
    /// hundreds. Tubes then cycle rather than empty, and only the reserve runs down.</para>
    /// </summary>
    public int MagazineDepth;

    /// <summary>Seconds between consecutive rounds of a salvo.</summary>
    public float SalvoSpacing = 0.45f;

    /// <summary>Seconds to reload an empty launcher. Zero disables auto-reload.</summary>
    public float ReloadSeconds = 12f;

    /// <summary>
    /// Eject along the tube rather than slewing onto the target at launch. Only sensible for a
    /// launcher that aims; a fixed one has to slew, and wants <see cref="LaunchLoft"/>.
    /// </summary>
    public bool LaunchAlongTube = true;

    /// <summary>Bias toward the boresight for launchers that cannot aim. See FireGeometry.</summary>
    public float LaunchLoft = 0.35f;

    /// <summary>
    /// How hard a round is pushed off its rail as it leaves, as a fraction of the tube axis,
    /// along the launcher's boresight.
    ///
    /// <para>Only applies when rounds leave along the tube. A rail has no tube walls to hold the
    /// round, so it separates outward as well as forward — without which it departs along the
    /// skin of whatever it is bolted to. Zero for a launcher whose rounds are ejected from a
    /// container, which is why it does not change the Pantsir.</para>
    /// </summary>
    public float EjectAwayFromMount;

    /// <summary>Standoff used when no launcher part is fitted at all (m).</summary>
    public float MuzzleOffset = 8f;

    // ---- Cannon ---------------------------------------------------------

    /// <summary>
    /// Registry key of the round the cannon fire, or null for a launcher with none.
    ///
    /// <para>A second weapon on the same mount rather than a second launcher: it shares the
    /// platform, the sensor and the aim, and differs in what it throws and how far.</para>
    /// </summary>
    public string? GunMunition { get; init; }

    /// <summary>Each barrel's muzzle in the cannon subpart's own frame, at its modelled pose.</summary>
    public double3[] GunMuzzles { get; init; } = [];

    /// <summary>Rounds in the belt, across all barrels.</summary>
    public int GunAmmo = 480;

    /// <summary>Cyclic rate, rounds per minute across all barrels.</summary>
    public float GunRoundsPerMinute = 2500f;

    /// <summary>Rounds per burst, and the pause between bursts.</summary>
    public int GunBurstRounds = 12;
    public float GunBurstGapSeconds = 0.55f;

    /// <summary>Seconds to feed a fresh belt. Zero disables cannon resupply.</summary>
    public float GunReloadSeconds = 20f;

    /// <summary>Seconds between rounds, derived from the cyclic rate.</summary>
    public double GunRoundInterval => GunRoundsPerMinute > 0f ? 60.0 / GunRoundsPerMinute : 0.0;

    /// <summary>True when this launcher carries cannon that can actually shoot.</summary>
    public bool HasCannon => GunMunition is not null && GunMuzzles.Length > 0;

    /// <summary>Turret drive rates in the units the drive wants.</summary>
    public double SlewRateRad => float.DegreesToRadians(SlewRateDeg);
    public double ElevationRateRad => float.DegreesToRadians(ElevationRateDeg);

    /// <summary>Applies this profile's travel limits to a drive.</summary>
    public void ConfigureTurret(Turret turret)
    {
        turret.MinElevationRad = float.DegreesToRadians(MinElevationDeg);
        turret.MaxElevationRad = float.DegreesToRadians(MaxElevationDeg);
        turret.ForwardMinElevationRad = float.DegreesToRadians(ForwardMinElevationDeg);
        turret.ForwardArcRad = float.DegreesToRadians(ForwardArcDeg);
        turret.ForwardPlateauRad = float.DegreesToRadians(ForwardPlateauDeg);
        turret.RestElevationRad = RestElevationRad;
    }
}
