using Brutal.Numerics;

namespace KSArmory;

/// <summary>
/// One optical head: where it sits, how fast it turns, and what it sees with.
///
/// <para>Its own profile type rather than fields on <see cref="LauncherProfile"/>, because a head
/// is no longer part of a launcher. It bolts to anything, finds its own targets and drives the
/// player's view, so a craft carrying nothing else is an observation post.</para>
///
/// <para>Two bodies and no named axes. A head is aimed by the shortest rotation onto the
/// commanded direction — see <see cref="PointingDrive"/> — which has no singularity looking
/// straight up, and that is where an air-defence sight spends its time. A turret expressed as
/// bearing and elevation cannot do that job.</para>
/// </summary>
public sealed class OpticProfile
{
    public required string PartId { get; init; }
    public required string DisplayName { get; init; }

    /// <summary>Which <see cref="SensorProfile"/> it finds things with.</summary>
    public required string Sensor { get; init; }

    /// <summary>Subpart marker for the fixed flange and mast.</summary>
    public required string BaseMarker { get; init; }

    /// <summary>Subpart marker for the gimballed head.</summary>
    public required string HeadMarker { get; init; }

    /// <summary>
    /// Where the head turns, as an offset from the <em>base</em> — not a point in the part.
    ///
    /// <para>The two are the same number for a director bolted to a hull, whose base sits at the
    /// part origin, and differ for one riding a turret. Carrying it onto wherever the base
    /// actually is belongs to <see cref="MountFrame.ToPart"/>, which is why a head that rides
    /// something needs nothing here.</para>
    ///
    /// <para>Generated by <c>tools/model/optic.py</c>; the mesh is exported recentred on it and the
    /// asset XML puts it back, so all three have to agree and <c>tools/validate-parts.py</c> checks
    /// that they do.</para>
    /// </summary>
    public required double3 HeadPivot { get; init; }

    /// <summary>
    /// How far in front of the pivot the eye sits (m).
    ///
    /// <para>Along the aim, so it slides the camera up and down the line of sight and contributes
    /// nothing to where the picture points. The perpendicular part is what would, which is why
    /// the bearing is measured from <see cref="HeadPivot"/> and not from the part's origin.</para>
    /// </summary>
    public float EyeForward = 0.30f;

    /// <summary>
    /// How fast the head slews (deg/s). The rate limit is the whole point: writing the commanded
    /// direction straight to the part snaps the head onto a track the instant there is one, which
    /// reads as a fault rather than as a sight.
    /// </summary>
    public float SlewRateDeg = 90f;

    /// <summary>
    /// How far down the head may look (deg, negative below the mounting face).
    ///
    /// <para>Not a preference. The window and its hood stand off the pivot by more than the mast
    /// stops short of it, so a head pointed straight down puts its lens through its own mount. No
    /// geometry fixes that — a ball on a mast cannot see past what holds it up — which is why a
    /// real director has the same limit for the same reason.</para>
    /// </summary>
    public float MinElevationDeg = -20f;

    /// <summary>How far up. Short of straight up, where a pointing head has nothing to roll about.</summary>
    public float MaxElevationDeg = 85f;

    public double SlewRateRad => float.DegreesToRadians(SlewRateDeg);
}
