using Brutal.Numerics;

namespace KSArmory;

/// <summary>
/// How a head is hung. It decides three things a caller cannot infer from the geometry: which
/// axis the travel limits are measured from, which roll the mesh is given, and where the head
/// parks when it has nothing to look at.
/// </summary>
public enum GimbalKind
{
    /// <summary>
    /// A ball on a mast, free to point anywhere its mast leaves clear. Travel is elevation over
    /// the mounting face, and the roll keeps the ball's own up as near the mount's normal as the
    /// aim allows.
    /// </summary>
    Mast,

    /// <summary>
    /// Roll-nod, which is what a targeting pod has: the whole nose turns continuously about the
    /// pod's own centreline, and the line of sight tilts within that turning frame.
    ///
    /// <para>Two mechanical reasons it is not azimuth-elevation. The roll axis carries its mass
    /// close to the axis of symmetry, so it slews and settles far faster for the same mass; and a
    /// body of revolution keeps one drag profile whichever way it looks, where an az-el head has
    /// to be a ball hanging out of a fairing.</para>
    ///
    /// <para>The cost is the <b>keyhole</b>. Dead along the roll axis the outer gimbal is
    /// degenerate — a target crossing the nose needs unbounded roll rate, and one exactly on the
    /// axis has no roll angle at all. That is the same singularity an alt-az telescope has at
    /// zenith, and it is why <see cref="OpticProfile.KeyholeDeg"/> keeps the command out of it
    /// rather than leaving the collar to spin.</para>
    /// </summary>
    RollNod,
}

/// <summary>
/// One optical head: where it sits, how fast it turns, and what it sees with.
///
/// <para>Its own profile type rather than fields on <see cref="LauncherProfile"/>, because a head
/// is no longer part of a launcher. It bolts to anything, finds its own targets and drives the
/// player's view, so a craft carrying nothing else is an observation post.</para>
///
/// <para>Two bodies and no named axes. A head is aimed by the shortest rotation onto the
/// commanded direction — see <see cref="PointingDrive"/> — which has no singularity looking
/// straight up, and that is where an air-defence sight spends its time. A turret expressed as
/// bearing and elevation cannot do that job.</para>
/// </summary>
public sealed class OpticProfile
{
    public required string PartId { get; init; }
    public required string DisplayName { get; init; }

    /// <summary>Which <see cref="SensorProfile"/> it finds things with.</summary>
    public required string Sensor { get; init; }

    /// <summary>How it is hung, which is what every travel and roll question below branches on.</summary>
    public GimbalKind Gimbal { get; init; } = GimbalKind.Mast;

    /// <summary>Subpart marker for the fixed flange and mast.</summary>
    public required string BaseMarker { get; init; }

    /// <summary>Subpart marker for the gimballed head.</summary>
    public required string HeadMarker { get; init; }

    /// <summary>
    /// Subpart marker for the outer roll gimbal, or null for a head that has none.
    ///
    /// <para>Only a <see cref="GimbalKind.RollNod"/> head has an outer body to write: it is the
    /// shell the window nods inside, and it turns about the pod's centreline alone. Leaving it
    /// null on a mast head is not an omission — there is no such body — so nothing looks for one
    /// and no warning is due when it is absent.</para>
    /// </summary>
    public string? RollMarker { get; init; }

    /// <summary>
    /// Where the head turns, as an offset from the <em>base</em> — not a point in the part.
    ///
    /// <para>The two are the same number for a director bolted to a hull, whose base sits at the
    /// part origin, and differ for one riding a turret. Carrying it onto wherever the base
    /// actually is belongs to <see cref="MountFrame.ToPart"/>, which is why a head that rides
    /// something needs nothing here.</para>
    ///
    /// <para>Generated by <c>tools/model/optic.py</c>; the mesh is exported recentred on it and the
    /// asset XML puts it back, so all three have to agree and <c>tools/validate-parts.py</c> checks
    /// that they do.</para>
    /// </summary>
    public required double3 HeadPivot { get; init; }

    /// <summary>
    /// How far in front of the pivot the eye sits (m).
    ///
    /// <para>Along the aim, so it slides the camera up and down the line of sight and contributes
    /// nothing to where the picture points. The perpendicular part is what would, which is why
    /// the bearing is measured from <see cref="HeadPivot"/> and not from the part's origin.</para>
    /// </summary>
    public float EyeForward = 0.30f;

    /// <summary>
    /// How fast the head slews (deg/s). The rate limit is the whole point: writing the commanded
    /// direction straight to the part snaps the head onto a track the instant there is one, which
    /// reads as a fault rather than as a sight.
    /// </summary>
    public float SlewRateDeg = 90f;

    /// <summary>
    /// How far down the head may look (deg, negative below the mounting face).
    ///
    /// <para>Not a preference. The window and its hood stand off the pivot by more than the mast
    /// stops short of it, so a head pointed straight down puts its lens through its own mount. No
    /// geometry fixes that — a ball on a mast cannot see past what holds it up — which is why a
    /// real director has the same limit for the same reason.</para>
    /// </summary>
    public float MinElevationDeg = -20f;

    /// <summary>How far up. Short of straight up, where a pointing head has nothing to roll about.</summary>
    public float MaxElevationDeg = 85f;

    /// <summary>
    /// How far off the pod's own centreline a <see cref="GimbalKind.RollNod"/> head may look
    /// (deg). Ignored by a <see cref="GimbalKind.Mast"/> head, whose travel is an elevation band.
    ///
    /// <para>The one number that describes a roll-nod field of regard, because 360° of roll makes
    /// every bearing the same bearing: what is left is how far the nod tilts the line of sight
    /// away from dead ahead, and 90° is already the whole hemisphere below the aircraft.</para>
    /// </summary>
    public float MaxOffBoresightDeg = 135f;

    /// <summary>
    /// The cone dead ahead a roll-nod head will not enter (deg). Ignored by a mast head.
    ///
    /// <para>A guard rather than a preference: on the axis the roll angle is undefined, and near
    /// it a target crossing the nose asks the outer gimbal for a roll rate that grows without
    /// bound. Holding the command this far off keeps the collar's angle continuous, which is what
    /// stops the whole nose snapping round as the aim creeps past the axis.</para>
    /// </summary>
    public float KeyholeDeg = 4f;

    public double SlewRateRad => float.DegreesToRadians(SlewRateDeg);
}
