#!/usr/bin/env python3
"""Records which tests are studies rather than guards.

    ./tools/check-studies.py            # regenerate tests/KSArmory.Tests/STUDIES.md
    ./tools/check-studies.py --check    # fail if the committed record is stale (for CI)

`[Trait("kind", "study")]` takes a test out of the loop `tools/test.sh` runs on every push. The
tag is a label and nothing verifies it is honest, so a test that genuinely guards a behaviour can
be tagged by mistake and stop running locally -- silently, because the suite goes green with one
fewer test in it and nobody counts.

This does not decide whether a tag is right; nothing mechanical can. A study asserts that the
flight completed and writes its finding out for a reader, while a guard asserts a measured bound,
and both are spelled `Assert.True(...)`. Telling them apart means reading what the number means.

What it does instead is make the set *visible*. The record is committed, so tagging a test puts a
line in the author's own diff, where the question "is this really a study?" gets asked by a human
at the moment it can still be answered cheaply. ProbeCrossingFloorTests is the case in point: it
sweeps slopes and prints a table like every study here, and it is the only thing holding
IcbmConfig.PredictionStopsOnTheSurface to `Mean(on) < Mean(off) * 0.35`.

The blast radius is bounded either way -- ci.yml runs `test.sh --studies` as its own step, so a
mis-tagged guard is caught before a merge rather than never. This buys back the push loop.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TESTS = REPO / "tests" / "KSArmory.Tests"
OUT = TESTS / "STUDIES.md"

TRAIT = re.compile(r'\[Trait\("kind",\s*"study"\)\]')
CLASS = re.compile(r"^\s*(?:public|internal)\s+(?:sealed\s+)?class\s+(\w+)")
TEST = re.compile(r"^\s*\[(?:Fact|Theory)[\](]")
METHOD = re.compile(r"^\s*(?:public|private|internal)\s+(?:async\s+)?\w[\w<>,.\[\] ]*\s+(\w+)\s*\(")


def studies():
    """Every test carrying the trait, by class and method, as `Class.Method`."""
    found = []
    for path in sorted(TESTS.glob("*.cs")):
        cls = None
        class_wide = False
        pending = []
        for line in path.read_text().splitlines():
            if TRAIT.search(line):
                pending.append("trait")
                continue
            m = CLASS.match(line)
            if m:
                cls = m.group(1)
                # A trait sitting above the class declaration covers every test in it.
                class_wide = "trait" in pending
                pending = []
                continue
            if TEST.match(line):
                pending.append("test")
                continue
            m = METHOD.match(line)
            if m and "test" in pending:
                if class_wide or "trait" in pending:
                    found.append(f"{cls}.{m.group(1)}")
                pending = []
                continue
            # Anything else that is not an attribute or a comment ends the run of attributes.
            if line.strip() and not line.lstrip().startswith(("[", "//", "///", "*", "/*")):
                pending = []
    return sorted(found)


def render(names):
    lines = [
        "# Studies",
        "",
        "**Generated by `tools/check-studies.py` -- do not edit.**",
        "",
        "These carry `[Trait(\"kind\", \"study\")]`, so `./tools/test.sh` leaves them out of the",
        "loop that runs on every push. They measure a term of the flight model and write the",
        "finding out for a reader; their only assertions are that the flight completed.",
        "`./tools/test.sh --studies` runs them, and `ci.yml` has a step that does the same, so",
        "nothing here goes unrun before a merge.",
        "",
        "A line appearing below is a claim that the test guards nothing. That is worth a second",
        "look in review: `ProbeCrossingFloorTests` reads exactly like a study and is not.",
        "",
        f"{len(names)} tests:",
        "",
    ]
    lines += [f"- `{n}`" for n in names]
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv
    rendered = render(studies())

    if not check:
        OUT.write_text(rendered)
        print(f"wrote {OUT.relative_to(REPO)}")
        return 0

    committed = OUT.read_text() if OUT.exists() else ""
    if committed == rendered:
        n = len(studies())
        print(f"the study set matches the record ({n} tests)")
        return 0

    was = {l for l in committed.splitlines() if l.startswith("- `")}
    now = {l for l in rendered.splitlines() if l.startswith("- `")}
    for line in sorted(now - was):
        print(f"  newly tagged a study: {line[3:-1]}")
    for line in sorted(was - now):
        print(f"  no longer a study:    {line[3:-1]}")
    print()
    print("  A tagged test stops running on every push. If any of the above guards a behaviour")
    print("  -- asserts a measured bound rather than that the flight completed -- take the trait")
    print("  off it. If they really are studies, commit the record:")
    print()
    print("      ./tools/check-studies.py")
    return 1


if __name__ == "__main__":
    sys.exit(main())
