#!/usr/bin/env python3
"""Every setting a player is meant to reach must have a control that reaches it.

A field added to SensorProfile, MunitionProfile or SystemConfig is live the moment it exists:
the code reads it, the docs describe it, it ships. What does not happen on its own is a control
in the panel, because Ksa/Ui enumerates them by hand -- so the field is real, documented,
shipped, and no player can touch it. Nothing fails, and nothing in the log says so.

That is not hypothetical. SensorProfile.HorizonMasking and TerrainMarginMetres shipped that way,
and a whole section of CHECKLIST.md asked for them to be toggled.

Textual, like check-boundary.sh and check-network.sh, and for the same reason: the panel is under
Ksa/ and the test project cannot reference it, so a test can never see this.

The exceptions are listed here with a reason each. A field is only exempt if a control would be
meaningless -- geometry generated by the model scripts, a value derived from another, or an
identity string -- never because nobody has got round to it.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SIM = REPO / "src" / "KSArmory" / "Sim"
UI = REPO / "src" / "KSArmory" / "Ksa" / "Ui"

# The types whose members a player is meant to be able to reach.
TUNABLE = ["SensorProfile", "MunitionProfile", "SystemConfig", "OpticConfig"]

# Members the panel drives through a helper rather than by name -- a tick box bound to a `ref` the
# helper returns. The value is what must appear in the panel instead, so removing the control still
# fails the check. An exemption would not: it would claim no control could reach the setting, which
# is the opposite of the truth here.
VIA = {
    "SystemConfig.MissilesEnabled": "EnabledIn",
    "SystemConfig.GunsEnabled": "EnabledIn",

    # A policy object rather than a value: the reference never changes and the panel writes what
    # is inside it. Its own team is the field that decides every classification, so it stands for
    # the group -- the teams pane is gone if that write is gone.
    "SystemConfig.Iff": "Iff.OwnTeam",

    # A director's own allegiance, edited on its own row under the Director tab. Its own,
    # because a head finds its own targets and a craft can carry one with no armament.
    "OpticConfig.Iff": "Iff.OwnTeam",

    # The scope's window is opened from the sensor's component row, through the same one-window-
    # at-a-time helper the director's map uses. The button is the control; TakeScope is how it
    # writes, and it also shuts everyone else's.
    "SystemConfig.ScopeOpen": "TakeScope",

    # The range detents are drawn from a table rather than as one named write, so the control is a
    # loop over ScopeRanges. Deleting it deletes the only caller.
    "SystemConfig.ScopeRangeMetres": "DrawScopeControls",
}

# Members no control could sensibly reach, and why. Anything not here needs one.
EXEMPT = {
    "SensorProfile.BoresightSource":
        "which way the set looks is the weapon's design, not a setting",
    "SensorProfile.Emits":
        "whether a set transmits at all is what kind of set it is; the operator's switch for "
        "whether it is transmitting *now* is SystemConfig.RadarSilent, which has a control",

    "MunitionProfile.BodyLength":
        "generated by the model script; validate-parts.py holds it to the mesh",
    "MunitionProfile.FinStowedScale":
        "how a fin is hidden before it deploys, which is art rather than performance",
    "MunitionProfile.FinDeploySeconds":
        "as above",
    "MunitionProfile.Stages":
        "a boost schedule is a table, not a slider",
    "MunitionProfile.MaxFaithfulStepSeconds":
        "the integrator's own limit; WarpPolicy reads it and a player must not raise it",
    "MunitionProfile.DragK":
        "ballistic coefficient, which belongs to the round rather than to the operator",
    "MunitionProfile.NeutralDensityRatio":
        "as above",
    "MunitionProfile.HitsTerrain":
        "costs a terrain sample per round per frame; a weapon's design, not a preference",
    "MunitionProfile.TimedFuse":
        "the flak fuse of a secondary armament, set under Tuning -> Warhead",
    "MunitionProfile.Guidance":
        "decides what the round *is* -- an Interceptor or a Slug -- rather than how well it flies",

    "SystemConfig.MouseFire":
        "a tool that fires, deliberately not persisted",
}

MEMBER = re.compile(
    r"^\s*public\s+(?!static\b|const\b)"
    r"(?:required\s+)?"
    r"(?P<type>[\w.<>?\[\], ]+?)\s+"
    r"(?P<name>\w+)\s*"
    r"(?P<tail>[={;]|\{\s*get)"
)


def members(type_name):
    """Every stored, settable public member of a type, in declaration order."""
    path = SIM / f"{type_name}.cs"
    if not path.is_file():
        print(f"error: {path} not found", file=sys.stderr)
        return None

    found = []
    inside = False
    for line in path.read_text().splitlines():
        if not inside:
            inside = re.search(rf"\b(class|record|struct)\s+{type_name}\b", line) is not None
            continue

        match = MEMBER.match(line)
        if match is None:
            continue

        name = match.group("name")

        # A property with a body is derived from something else, and setting it means nothing.
        # `init` and `required` are identity, fixed when the profile is written down.
        if "=>" in line or " init;" in line or "required" in match.group(0):
            continue

        # A get-only property holds a collection the panel edits through, not a value it sets.
        if match.group("tail").startswith("{") and "set" not in line:
            if name not in found:
                found.append(name)
            continue

        if name not in found:
            found.append(name)

    return found


# What the panel calls each type. Required in the pattern, because matching a bare member name
# lets one type's control satisfy another's: SystemConfig and OpticConfig share Iff, MouseAim and
# ProtectControlledVehicle, and the weapon's controls were standing in for the director's. Both of
# the director's were unreachable while this check reported green.
#
# `\b` keeps `policy` from matching inside `_policy`: `_` is a word character, so there is no
# boundary between it and what follows.
RECEIVERS = {
    "SensorProfile": ("_sensor",),
    "MunitionProfile": ("_munition", "round"),
    "SystemConfig": ("_policy",),
    "OpticConfig": ("policy",),
}


def written(panel, name, receivers):
    """Whether the panel *writes* the member on the right object, rather than mentioning it.

    Mentioning is not reaching. Every one of these controls is followed by a line reading the
    value back to explain what it just did -- `if (_sensor.NotchSpeed > 0f)` and the like -- so a
    check that accepted any occurrence would pass with the slider deleted and the explanation
    left behind, which is exactly the state it exists to catch.
    """
    for receiver in receivers:
        at = rf"\b{re.escape(receiver)}\.{re.escape(name)}"

        # ImGui binds a control to a field by reference; a radio button assigns outright.
        if re.search(rf"\bref\s+{at}\b", panel) is not None: return True
        if re.search(rf"{at}\s*=(?!=)", panel) is not None: return True

    return False


def written_via(panel, helper, receivers):
    """The same question for a member the panel drives through a helper.

    A dotted path is still a write on the object, so it keeps the receiver -- that is what makes
    `policy.Iff.OwnTeam` a different claim from `_policy.Iff.OwnTeam`. A bare name is a helper
    taking the object as an argument, where the receiver is the helper's own type and requiring
    it would defeat the point.
    """
    if "." in helper:
        return written(panel, helper.split(".", 1)[0] + "." + helper.split(".", 1)[1], receivers) \
            or any(re.search(rf"\b{re.escape(r)}\.{re.escape(helper)}\s*=(?!=)", panel)
                   for r in receivers)

    return re.search(rf"\b{re.escape(helper)}\s*\(", panel) is not None


def main():
    if not UI.is_dir():
        print(f"error: {UI} not found", file=sys.stderr)
        return 1

    panel = "\n".join(p.read_text() for p in sorted(UI.glob("*.cs")))

    problems = 0
    checked = 0
    exempted = 0

    for type_name in TUNABLE:
        found = members(type_name)
        if found is None:
            return 1

        print(f"{type_name}: {len(found)} settable member(s)")

        for name in found:
            key = f"{type_name}.{name}"
            if key in EXEMPT:
                exempted += 1
                continue

            checked += 1
            receivers = RECEIVERS[type_name]
            wanted = VIA.get(key)

            reached = written_via(panel, wanted, receivers) if wanted is not None \
                else written(panel, name, receivers)

            if not reached:
                how = f"nothing in Ksa/Ui writes through {wanted}" if key in VIA \
                    else f"no control in Ksa/Ui writes {'/'.join(receivers)}.{name}"
                print(f"  UNREACHABLE {key} -- {how}", file=sys.stderr)
                problems += 1

    # Named rather than counted, so an exemption cannot be left behind quietly once the member it
    # excused has gone -- which is how an exemption list turns into a list nobody trusts.
    for table, label in ((EXEMPT, "EXEMPTION"), (VIA, "INDIRECTION")):
        for key in table:
            type_name, _, name = key.partition(".")
            if type_name not in TUNABLE:
                continue
            if name not in (members(type_name) or []):
                print(f"  STALE {label} {key} -- no such member any more", file=sys.stderr)
                problems += 1

    print()
    if problems:
        print(f"FAILED: {problems} setting(s) a player cannot reach", file=sys.stderr)
        print("        add a control in src/KSArmory/Ksa/Ui, or an exemption with a reason",
              file=sys.stderr)
        return 1

    print(f"OK: {checked} setting(s) reachable, {exempted} exempt with a reason")
    return 0


if __name__ == "__main__":
    sys.exit(main())
